/**
 * Desktop shortcut management.
 *
 * Windows: creates a "DeepSeek Harness.lnk" on the Desktop whose icon is
 * assets/deepseek-whale-black.ico (the black whale). The shortcut runs a
 * tiny generated VBS launcher (start-silent.vbs) so that double-clicking
 * starts the harness without a console window; failures pop a message box
 * pointing at the log file.
 *
 * Linux: writes a .desktop entry (Desktop + ~/.local/share/applications)
 * with the 256px whale icon.
 *
 * macOS: builds a minimal "DeepSeek Harness.app" bundle in ~/Applications
 * (LSUIElement, black whale icns icon) and links it on the Desktop; the app
 * simply runs `node bin/launcher.mjs start`.
 */
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { launcherRoot } from './paths.mjs';

export const SHORTCUT_NAME = 'DeepSeek Harness';
export const WINDOWS_ICON = 'assets/deepseek-whale-black.ico';
export const LINUX_ICON = 'assets/whale-black.png';
export const MAC_ICON = 'assets/whale-black.icns';

const WINDOWS = process.platform === 'win32';
const DARWIN = process.platform === 'darwin';

function vbString(s) {
  return `"${String(s).replace(/"/g, '""')}"`;
}

function runVbs(script, args = []) {
  const tmp = path.join(os.tmpdir(), `dsh-launcher-${process.pid}-${Date.now()}.vbs`);
  fs.writeFileSync(tmp, script, 'utf8');
  try {
    const res = spawnSync('cscript.exe', ['//nologo', tmp, ...args], {
      windowsHide: true,
      encoding: 'utf8',
    });
    if (res.status !== 0) {
      throw new Error(`cscript failed (exit ${res.status}): ${res.stderr ?? res.stdout ?? ''}`);
    }
    return (res.stdout ?? '').trim();
  } finally {
    fs.rmSync(tmp, { force: true });
  }
}

/** Resolve the real Desktop directory (honours OneDrive redirection). */
export function getDesktopPath() {
  if (WINDOWS) {
    const res = spawnSync(
      'powershell.exe',
      ['-NoProfile', '-NonInteractive', '-Command', '[Environment]::GetFolderPath("Desktop")'],
      { windowsHide: true, encoding: 'utf8' },
    );
    const out = (res.stdout ?? '').trim();
    if (res.status === 0 && out) return out;
    return path.join(os.homedir(), 'Desktop');
  }
  if (DARWIN) return path.join(os.homedir(), 'Desktop');
  const xdg = process.env.XDG_DESKTOP_DIR;
  if (xdg) return xdg;
  const userDirs = path.join(os.homedir(), '.config', 'user-dirs.dirs');
  try {
    const text = fs.readFileSync(userDirs, 'utf8');
    const match = text.match(/XDG_DESKTOP_DIR="([^"]+)"/);
    if (match) return match[1].replace('$HOME', os.homedir());
  } catch {
    /* fall through */
  }
  return path.join(os.homedir(), 'Desktop');
}

/** The shortcut location this platform installs. */
export function shortcutPath() {
  if (WINDOWS) return path.join(getDesktopPath(), `${SHORTCUT_NAME}.lnk`);
  if (DARWIN) return macAppDir();
  return path.join(getDesktopPath(), 'deepseek-harness.desktop');
}

export function shortcutExists() {
  return fs.existsSync(shortcutPath());
}

// ---------------------------------------------------------------------------
// Windows
// ---------------------------------------------------------------------------

function writeSilentLauncher() {
  const root = launcherRoot();
  const target = path.join(root, 'start-silent.vbs');
  const launcher = path.join(root, 'bin', 'launcher.mjs');
  const script = [
    `' DeepSeek Harness silent launcher — generated by "dsh-launcher install".`,
    `' Re-run "dsh-launcher install" after moving this folder.`,
    `Option Explicit`,
    `Dim sh, code, cmd, logPath, msg`,
    `Set sh = CreateObject("WScript.Shell")`,
    `cmd = """" & "node" & """ """ & ${vbString(launcher)} & """ start"`,
    `On Error Resume Next`,
    `code = sh.Run(cmd, 0, True)`,
    `If Err.Number <> 0 Or code <> 0 Then`,
    `  logPath = sh.ExpandEnvironmentStrings("%USERPROFILE%") & "\\.dsh-launcher\\run\\web.log"`,
    `  msg = "DeepSeek Harness failed to start." & vbCrLf & vbCrLf & _`,
    `        "Exit code: " & CStr(code) & vbCrLf & _`,
    `        "Log file: " & logPath`,
    `  MsgBox msg, 48, "DeepSeek Harness Launcher"`,
    `End If`,
    ``,
  ].join('\r\n');
  fs.writeFileSync(target, script, 'utf8');
  return target;
}

function installWindows({ force, t, log }) {
  const root = launcherRoot();
  const iconPath = path.join(root, WINDOWS_ICON);
  if (!fs.existsSync(iconPath)) throw new Error(t('doctor.iconNone'));

  const vbs = writeSilentLauncher();
  log(t('shortcut.vbsWritten', { path: vbs }));

  if (!force && shortcutExists()) {
    log(t('shortcut.already', { name: SHORTCUT_NAME }));
    return { installed: false, exists: true };
  }

  log(t('shortcut.installing', { name: SHORTCUT_NAME }));
  const script = [
    'Option Explicit',
    'Dim sh, sc, desktop, root, icon',
    'Set sh = CreateObject("WScript.Shell")',
    'desktop = sh.SpecialFolders("Desktop")',
    `root = ${vbString(root)}`,
    `icon = ${vbString(iconPath)}`,
    `Set sc = sh.CreateShortcut(desktop & "\\${SHORTCUT_NAME}.lnk")`,
    'sc.TargetPath = "C:\\Windows\\System32\\wscript.exe"',
    `sc.Arguments = """" & root & "\\start-silent.vbs" & """"`,
    'sc.WorkingDirectory = root',
    'sc.IconLocation = icon & ",0"',
    `sc.Description = "Start DeepSeek Harness web UI (dsh web)"`,
    'sc.WindowStyle = 1',
    'sc.Save',
  ].join('\r\n');
  runVbs(script);
  log(t('shortcut.installed', { name: SHORTCUT_NAME }));
  return { installed: true };
}

function uninstallWindows({ t, log }) {
  const script = [
    'Option Explicit',
    'Dim sh, fso, desktop, p',
    'Set sh = CreateObject("WScript.Shell")',
    'Set fso = CreateObject("Scripting.FileSystemObject")',
    'desktop = sh.SpecialFolders("Desktop")',
    `p = desktop & "\\${SHORTCUT_NAME}.lnk"`,
    'If fso.FileExists(p) Then',
    '  fso.DeleteFile p, True',
    '  WScript.Echo "deleted"',
    'Else',
    '  WScript.Echo "missing"',
    'End If',
  ].join('\r\n');
  const result = runVbs(script);
  if (result === 'deleted') log(t('shortcut.uninstalled', { name: SHORTCUT_NAME }));
  else log(t('shortcut.missing', { name: SHORTCUT_NAME }));
  return { uninstalled: result === 'deleted' };
}

// ---------------------------------------------------------------------------
// Linux
// ---------------------------------------------------------------------------

function installLinux({ force, t, log }) {
  const root = launcherRoot();
  const iconSource = path.join(root, LINUX_ICON);
  const iconTargetDir = path.join(os.homedir(), '.local', 'share', 'icons', 'hicolor', '256x256', 'apps');
  const iconTarget = path.join(iconTargetDir, 'whale-black.png');
  fs.mkdirSync(iconTargetDir, { recursive: true });
  fs.copyFileSync(iconSource, iconTarget);

  const nodeBin = process.execPath;
  const content = [
    '[Desktop Entry]',
    'Type=Application',
    'Version=1.0',
    `Name=${SHORTCUT_NAME}`,
    'Comment=Start the DeepSeek Harness web UI (dsh web)',
    `Exec=${nodeBin} ${path.join(root, 'bin', 'launcher.mjs')} start`,
    'Icon=whale-black',
    'Terminal=false',
    'Categories=Development;Utility;',
    '',
  ].join('\n');

  const desktopDir = getDesktopPath();
  const desktopFile = path.join(desktopDir, 'deepseek-harness.desktop');
  const applicationsDir = path.join(os.homedir(), '.local', 'share', 'applications');
  const applicationsFile = path.join(applicationsDir, 'deepseek-harness.desktop');

  if (!force && (fs.existsSync(desktopFile) || fs.existsSync(applicationsFile))) {
    log(t('shortcut.already', { name: SHORTCUT_NAME }));
    return { installed: false, exists: true };
  }

  fs.mkdirSync(applicationsDir, { recursive: true });
  fs.writeFileSync(applicationsFile, content, 'utf8');
  if (fs.existsSync(desktopDir)) {
    fs.writeFileSync(desktopFile, content, 'utf8');
    try {
      fs.chmodSync(desktopFile, 0o755);
    } catch {
      /* best effort */
    }
  }
  log(t('shortcut.linuxFiles', { desktop: desktopFile, applications: applicationsFile, icon: iconTarget }));
  return { installed: true };
}

function uninstallLinux({ t, log }) {
  const desktopFile = path.join(getDesktopPath(), 'deepseek-harness.desktop');
  const applicationsFile = path.join(os.homedir(), '.local', 'share', 'applications', 'deepseek-harness.desktop');
  let removed = false;
  for (const f of [desktopFile, applicationsFile]) {
    if (fs.existsSync(f)) {
      fs.rmSync(f, { force: true });
      removed = true;
    }
  }
  if (removed) log(t('shortcut.uninstalled', { name: SHORTCUT_NAME }));
  else log(t('shortcut.missing', { name: SHORTCUT_NAME }));
  return { uninstalled: removed };
}

// ---------------------------------------------------------------------------
// macOS
// ---------------------------------------------------------------------------

/** Directory of the installed app bundle (~/Applications/DeepSeek Harness.app). */
export function macAppDir(home = os.homedir()) {
  return path.join(home, 'Applications', `${SHORTCUT_NAME}.app`);
}

/** Generate the Info.plist for the minimal app bundle. */
export function macInfoPlist(version) {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    '<dict>',
    '  <key>CFBundleName</key>',
    `  <string>${SHORTCUT_NAME}</string>`,
    '  <key>CFBundleDisplayName</key>',
    `  <string>${SHORTCUT_NAME}</string>`,
    '  <key>CFBundleIdentifier</key>',
    `  <string>com.deepseek.harness.launcher</string>`,
    '  <key>CFBundleVersion</key>',
    `  <string>${version}</string>`,
    '  <key>CFBundleShortVersionString</key>',
    `  <string>${version}</string>`,
    '  <key>CFBundleIconFile</key>',
    '  <string>whale-black.icns</string>',
    '  <key>CFBundlePackageType</key>',
    '  <string>APPL</string>',
    '  <key>CFBundleExecutable</key>',
    '  <string>launch</string>',
    '  <key>LSUIElement</key>',
    '  <true/>',
    '</dict>',
    '</plist>',
    '',
  ].join('\n');
}

function shQuote(s) {
  return `'${String(s).replace(/'/g, `'\\''`)}'`;
}

/** Generate the app's executable: run the launcher with the exact node binary. */
export function macLaunchScript(nodeBin, launcherScript) {
  return [
    '#!/bin/sh',
    '# DeepSeek Harness launcher app — generated by "dsh-launcher install".',
    '# Re-run "dsh-launcher install" after moving the launcher folder.',
    `exec ${shQuote(nodeBin)} ${shQuote(launcherScript)} start`,
    '',
  ].join('\n');
}

function readVersion() {
  try {
    return JSON.parse(fs.readFileSync(path.join(launcherRoot(), 'package.json'), 'utf8')).version ?? '1.0.0';
  } catch {
    return '1.0.0';
  }
}

function installMac({ force, t, log }) {
  const root = launcherRoot();
  const iconSource = path.join(root, MAC_ICON);
  if (!fs.existsSync(iconSource)) throw new Error(t('doctor.iconNone'));

  if (!force && shortcutExists()) {
    log(t('shortcut.already', { name: SHORTCUT_NAME }));
    return { installed: false, exists: true };
  }

  log(t('shortcut.installing', { name: SHORTCUT_NAME }));

  // 1. Build the .app bundle in ~/Applications.
  const appDir = macAppDir();
  fs.rmSync(appDir, { recursive: true, force: true });
  const contents = path.join(appDir, 'Contents');
  fs.mkdirSync(path.join(contents, 'MacOS'), { recursive: true });
  fs.mkdirSync(path.join(contents, 'Resources'), { recursive: true });
  fs.writeFileSync(path.join(contents, 'Info.plist'), macInfoPlist(readVersion()), 'utf8');
  fs.copyFileSync(iconSource, path.join(contents, 'Resources', 'whale-black.icns'));
  const execFile = path.join(contents, 'MacOS', 'launch');
  fs.writeFileSync(execFile, macLaunchScript(process.execPath, path.join(root, 'bin', 'launcher.mjs')), 'utf8');
  fs.chmodSync(execFile, 0o755);

  // 2. Link it on the Desktop (symlink; Finder shows the app icon).
  const desktopDir = getDesktopPath();
  let alias = null;
  if (fs.existsSync(desktopDir)) {
    alias = path.join(desktopDir, `${SHORTCUT_NAME}.app`);
    fs.rmSync(alias, { force: true });
    try {
      fs.symlinkSync(appDir, alias, 'dir');
    } catch {
      alias = null; // desktop unavailable (e.g. no GUI); app still installed
    }
  }

  log(t('shortcut.macInstalled', { app: appDir, alias: alias ?? '' }));
  return { installed: true, app: appDir, alias };
}

function uninstallMac({ t, log }) {
  const appDir = macAppDir();
  const alias = path.join(getDesktopPath(), `${SHORTCUT_NAME}.app`);
  const hadApp = fs.existsSync(appDir);
  const hadAlias = fs.existsSync(alias) || fs.lstatSync(alias, { throwIfNoEntry: false })?.isSymbolicLink();
  fs.rmSync(appDir, { recursive: true, force: true });
  fs.rmSync(alias, { force: true });
  if (hadApp || hadAlias) log(t('shortcut.uninstalled', { name: SHORTCUT_NAME }));
  else log(t('shortcut.missing', { name: SHORTCUT_NAME }));
  return { uninstalled: hadApp || hadAlias };
}

// ---------------------------------------------------------------------------
// Entry points
// ---------------------------------------------------------------------------

export function installShortcut({ force = false, t, log = console.log }) {
  if (WINDOWS) return installWindows({ force, t, log });
  if (DARWIN) return installMac({ force, t, log });
  if (process.platform === 'linux') return installLinux({ force, t, log });
  log(t('shortcut.unsupported'));
  return { installed: false, unsupported: true };
}

export function uninstallShortcut({ t, log = console.log }) {
  if (WINDOWS) return uninstallWindows({ t, log });
  if (DARWIN) return uninstallMac({ t, log });
  if (process.platform === 'linux') return uninstallLinux({ t, log });
  log(t('shortcut.unsupported'));
  return { uninstalled: false, unsupported: true };
}
